### ISSUE TITLE
Add Debug / Toolbox Panel Toggle

### ISSUE THREAD

**Issue by chrisbalt** [winjs/grid#21]
Similar to the [Starbucks Style Guide](http://www.starbucks.com/static/reference/styleguide/), place the top debug/toolbox buttons inside a toggle-able, fixed-position menu.

**For example:**
![screen shot 2014-09-16 at 2 27 06 pm](https://cloud.githubusercontent.com/assets/376994/4295279/3a63f772-3de8-11e4-9c32-38c77d419466.png)

**Comment by kylezinter** [comment]
Closing, applies to demo site and not the grid itself but also went with the drawer fixed menu style which is live.
