### ISSUE TITLE
hidden/toggle?

### ISSUE THREAD

**Issue by IRun26Point2** [winjs/grid#87]
Is there any way to cause an element to be hidden on specific viewports?  for example, a left-toggle refiner menu on a narrow viewport should collapse into the hamburger.

**Comment by kylezinter** [comment]
We don't currently have that baked into the grid, we've been handling it on an individual basis. I can see the case for this being needed/desired more commonly though. I'll leave this issue open for now as consideration and possibly implement in the next day or two. Is this a common need you face?

**Comment by IRun26Point2** [comment]
decently common. being able to show/hide certain elements at certain breakpoints is common extension for a grid.  not saying you should do what the bootstrap grid does, but the .visible-* and hidden-* classes are very helpful for making a list turn into a dropdown on wide vs narrow viewports, or for making controls collapse into the hamburger/drawer, etc.

**Comment by blustemy** [comment]
Hi @kylezinter, I agree with @IRun26Point2 that would be really useful to have this feature implemented in the WinJS Grid. We have a lot of cases where we need to hide a grid column under a specific device width.

**Comment by kylezinter** [comment]
Makes sense @blustemy and @IRun26Point2, I'll get something whipped up today.

**Comment by kylezinter** [comment]
Closed with commit 453eb349db74b919b96a0bacf502e16a37bc4175
